sudo: true

language: python

matrix:
    include:
        - os: linux
          sudo: required
          python: 3.7
          dist: xenial
        - os: linux
          sudo: required
          python: 3.6
        - os: linux
          sudo: required
          python: 3.5
        - os: linux
          sudo: required
          python: 3.4
        - os: osx
          language: generic
          env: TOXENV=py37
        - os: osx
          language: generic
          env: TOXENV=py36
        - os: osx
          language: generic
          env: TOXENV=py35
        - os: osx
          language: generic
          env: TOXENV=py34

install:
  - bash .travis/install.sh
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then pip install -r dev-requirements.txt ; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then pip3 install -r dev-requirements.txt ; fi
  - python3 --version
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then python setup.py install ; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then python3 setup.py install ; fi

script:
  - which python
  - python -m pytest opem/Test --cov=opem --cov-report=term
after_success:
  - codecov
