language: python

matrix:
    include:
        - os: linux
          python: 3.7
          env: TOXENV=py37-linux
          dist: xenial

        - os: linux
          python: 3.6
          env: TOXENV=py36-linux
        
        - os: linux
          python: 3.5
          env: TOXENV=py35-linux
        
        - os: linux
          python: 3.4
          env: TOXENV=py34-linux
        
         - os: linux
          python: 3.7-dev
          dist: xenial
          
        - os: linux
          python: 3.8-dev
          dist: xenial
          
        - os: linux
          python: nightly
          dist: xenial
          
    allow_failures:
        - os: linux
          python: 3.4
          env: TOXENV=py34-linux
        
        - os: linux
          python: 3.7-dev
          dist: xenial
          
        - os: linux
          python: 3.8-dev
          dist: xenial
          
        - os: linux
          python: nightly
          dist: xenial
install: 
  - bash .travis/install.sh

script: 
  - bash .travis/test.sh

after_success:
  - codecov
